version: '3'
services:
  app:
    build: .
    volumes:
      - './config.json:/nullcatchan/config.json:ro'
      - './font.ttf:/nullcatchan/font.ttf:ro'
      - './data:/nullcatchan/data'
      - './ngwords.txt:/nullcatchan/ngwords.txt'
    restart: always
    environment:
      TZ: Asia/Tokyo
